### ISSUE TITLE
"module" field incorrectly exposes es6 syntax

### ISSUE THREAD

**Issue by alisd23** [mostjs/prelude#15]
The recent addition of the `module` field in #14 is not being used correctly.

The `module` field is suppose to point to code that *"has ES2015 module syntax but otherwise only syntax features that browser/node supports."* However the current module field points to the src folder - which still contains es6 features (e.g. `let`).

- https://webpack.js.org/guides/author-libraries/#final-steps
- https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features

Maybe it would be better to also transpile the source to a `lib` folder where the code is all es5 expect for the es6 import/export syntax. Then that `lib` code could be exposed via the `module` field.

**Comment by briancavalier** [comment]
Hi @alisd23, thanks!  I just opened #16.  Would you mind taking a look to see if it looks right?  The dist files won't be there, since our current convention in mostjs is not to include them.  If you want to check them, you can pull the branch, `npm install`, and then `npm run build`.

**Comment by alisd23** [comment]
@briancavalier Thanks for getting on it so quickly. It looks right to me :+1:

**Comment by briancavalier** [comment]
@alisd23 Cool, thanks for taking a look.  We'll merge and get a new release out later today.

**Comment by briancavalier** [comment]
@alisd23 Just published 1.5.2 with the new ES build.
